/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   lib/utils/boot.html
 */

/// <reference path="../../augment-types.d.ts" />

declare namespace Polymer {
}
