/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   paper-menu-button-animations.html
 */

/// <reference path="../polymer/types/polymer.d.ts" />
/// <reference path="../neon-animation/neon-animation-behavior.d.ts" />

interface PaperMenuGrowHeightAnimationElement extends Polymer.Element, Polymer.NeonAnimationBehavior {
  configure(config: any): any;
}

interface HTMLElementTagNameMap {
  "paper-menu-grow-height-animation": PaperMenuGrowHeightAnimationElement;
  "paper-menu-grow-width-animation": PaperMenuGrowWidthAnimationElement;
  "paper-menu-shrink-width-animation": PaperMenuShrinkWidthAnimationElement;
  "paper-menu-shrink-height-animation": PaperMenuShrinkHeightAnimationElement;
}

interface PaperMenuGrowWidthAnimationElement extends Polymer.Element, Polymer.NeonAnimationBehavior {
  configure(config: any): any;
}

interface PaperMenuShrinkWidthAnimationElement extends Polymer.Element, Polymer.NeonAnimationBehavior {
  configure(config: any): any;
}

interface PaperMenuShrinkHeightAnimationElement extends Polymer.Element, Polymer.NeonAnimationBehavior {
  configure(config: any): any;
}
