/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   paper-checked-element-behavior.js
 */


// tslint:disable:variable-name API description

declare module 'goog:npm.polymer.paperBehaviors.PaperCheckedElementBehavior' {

  import {PaperInkyFocusBehavior} from 'goog:npm.polymer.paperBehaviors.PaperInkyFocusBehavior'; // from //third_party/javascript/polymer/v2/paper-behaviors

  import {PaperRippleBehavior} from 'goog:npm.polymer.paperBehaviors.PaperRippleBehavior'; // from //third_party/javascript/polymer/v2/paper-behaviors

  /**
   * Use `PaperCheckedElementBehavior` to implement a custom element that has a
   * `checked` property similar to `IronCheckedElementBehavior` and is compatible
   * with having a ripple effect.
   */
  interface PaperCheckedElementBehavior extends PaperInkyFocusBehavior, IronCheckedElementBehavior {

    /**
     * Synchronizes the element's `active` and `checked` state.
     */
    _buttonStateChanged(): void;

    /**
     * Synchronizes the element's checked state with its ripple effect.
     */
    _checkedChanged(): void;
  }

  const PaperCheckedElementBehavior: object;

  export {PaperCheckedElementBehavior};
}
