/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   paper-menu-button.js
 */

/// <reference path="paper-menu-button-animations.d.ts" />

declare function value(): any;

declare function value(): any;


/**
 * The content element that is contained by the menu button, if any.
 *    
 */
declare function contentElement(): any;


/**
 * Toggles the drowpdown content between opened and closed.
 *    
 */
declare function toggle(): void;


/**
 * Make the dropdown content appear as an overlay positioned relative
 * to the dropdown trigger.
 *    
 */
declare function open(): void;


/**
 * Hide the dropdown content.
 *    
 */
declare function close(): void;


/**
 * When an `iron-select` event is received, the dropdown should
 * automatically close on the assumption that a value has been chosen.
 */
declare function _onIronSelect(event: CustomEvent|null): void;


/**
 * Closes the dropdown when an `iron-activate` event is received if
 * `closeOnActivate` is true.
 */
declare function _onIronActivate(event: CustomEvent|null): void;


/**
 * When the dropdown opens, the `paper-menu-button` fires `paper-open`.
 * When the dropdown closes, the `paper-menu-button` fires `paper-close`.
 */
declare function _openedChanged(opened: boolean, oldOpened: boolean): void;


/**
 * If the dropdown is open when disabled becomes true, close the
 * dropdown.
 */
declare function _disabledChanged(disabled: boolean): void;
