/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   subdir/auto-importer.js
 */


// tslint:disable:variable-name API description

export {autoImportFunction};

declare function autoImportFunction(p1: ClassA1, p2: ClassA2): ExternalPackageClass;

import {ClassA1} from '../module-a.js';

import {ClassA2} from '../module-a.js';

import {ExternalPackageClass} from '@polymer/external-package';
