/**
 * @license
 * Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 * This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 * The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 * The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 * Code distributed by Google as part of the polymer project is also
 * subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
 */

import {Descriptor} from './descriptor';

/**
 * Represents an import, such as an HTML import, an external script or style
 * tag, or an JavaScript import.
 *
 * @template N The AST node type
 */
export class ImportDescriptor<N> implements Descriptor {
  type: 'html-import' | 'html-script' | 'html-style' | string;

  /**
   * URL of the import, relative to the document containing the import.
   */
  url: string;

  /**
   * The AST node associated with this descriptor. This is required for correct
   * ordering of descriptors generated by different finders.
   */
  node: N;

  constructor(type: string, url: string, node: N) {
    this.type = type;
    this.url = url;
    this.node = node;
  }
}
