/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   paper-button.js
 */


// tslint:disable:variable-name API description

declare module 'goog:npm.polymer.paperButton.PaperButton' {

  import {PaperButtonBehavior} from 'goog:npm.polymer.paperBehaviors.PaperButtonBehavior'; // from //third_party/javascript/polymer/v2/paper-behaviors

  import {Polymer} from 'goog:npm.polymer.polymer.lib.legacy.PolymerFn'; // from //third_party/javascript/polymer/v2/polymer

  import {html} from 'goog:npm.polymer.polymer.PolymerLegacy'; // from //third_party/javascript/polymer/v2/polymer

  import {LegacyElementMixin} from 'goog:npm.polymer.polymer.lib.legacy.LegacyElementMixin'; // from //third_party/javascript/polymer/v2/polymer

  interface PaperButtonElement extends PaperButtonBehavior, LegacyElementMixin, HTMLElement {

    /**
     * If true, the button should be styled with a shadow.
     */
    raised: boolean|null|undefined;
    _calculateElevation(): void;
  }

  export {PaperButtonElement};

  global {

    interface HTMLElementTagNameMap {
      "paper-button": PaperButtonElement;
    }
  }
}
