/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   lib/legacy/polymer-fn.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

declare module 'goog:polymer.polymer.lib.legacy.polymerFn' {

  import {Class} from 'goog:polymer.polymer.lib.legacy.class'; // from //third_party/javascript/polymer/v2/polymer


  /**
   * Legacy class factory and registration helper for defining Polymer
   * elements.
   *
   * This method is equivalent to
   *
   *     import {Class} from '@polymer/polymer/lib/legacy/class.js';
   *     customElements.define(info.is, Class(info));
   *
   * See `Class` for details on valid legacy metadata format for `info`.
   *
   * @returns Generated class
   */
  function Polymer(info: PolymerInit): {new(): HTMLElement};

  export {Polymer};

  import {PolymerInit} from 'goog:polymer.polymer.interfaces'; // from //third_party/javascript/polymer/v2/polymer
}
