/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   combo.html
 *   combo.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

declare function B(): void;

declare function C(): void;

declare function A(): void;
