/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   module-b.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

export {ClassB1};

declare class ClassB1 {
}

export {ClassB2};

declare class ClassB2 {
}

export {ClassC1} from './module-c.js';

export {ClassC2 as ClassC2Alias} from './module-c.js';
