/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   my-class.js
 */


// tslint:disable:variable-name API description
// tslint:disable:no-any describes the API as best we are able today

declare class MyClass {
  dont_exclude_this_property: string;
  constructor(num: number, truth: boolean);
  no_params(): void;
  one_param(p1: any): void;
  two_params(p1: any, p2: any): void;
  typed_return(): boolean;
  two_typed_params_and_typed_return(p1: string, p2: number): boolean;
  typed_rest_param(...p1: string[]): void;
  undocumented_rest_param(...p1: any[]): void;
  optional_param(p1?: string): void;
  required_and_optional_param(p1: any, p2?: string): void;
  defaulted_param(p1?: any): void;
  defaulted_and_optional_param(p1?: any, p2?: string): void;
  defaulted_and_required_param(p1: any|undefined, p2: any): void;
  parameterized_return_type(): MyParameterizedType<boolean>;
  renamed_collection_return_types(): Array<NodeListOf<Node>|HTMLCollectionOf<HTMLElement>>;
}
