/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   my-element.html
 */

/**
 * I'm an HTML comment that contains JavaScript comments which must be escaped:
 *
 *   /** Danger! *\/
 *
 *   /** More danger! *\/*\/
 */
interface MyElementElement extends Polymer.LegacyElementMixin, HTMLElement {
}

interface HTMLElementTagNameMap {
  "my-element": MyElementElement;
  "my-sub-element": MySubElement;
}

declare class MySubElement extends Polymer.Element {

  /**
   * Some description
   */
  // @ts-ignore
  get(): void;
}
