/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   paper-menu-button-animations.html
 */


// tslint:disable:variable-name API description
// tslint:disable:no-any describes the API as best we are able today

/// <reference path="../polymer/types/polymer.d.ts" />
/// <reference path="../neon-animation/neon-animation-behavior.d.ts" />

interface PaperMenuGrowHeightAnimationElement extends Polymer.NeonAnimationBehavior, Polymer.LegacyElementMixin, HTMLElement {
  configure(config: any): any;
}

interface HTMLElementTagNameMap {
  "paper-menu-grow-height-animation": PaperMenuGrowHeightAnimationElement;
  "paper-menu-grow-width-animation": PaperMenuGrowWidthAnimationElement;
  "paper-menu-shrink-width-animation": PaperMenuShrinkWidthAnimationElement;
  "paper-menu-shrink-height-animation": PaperMenuShrinkHeightAnimationElement;
}

interface PaperMenuGrowWidthAnimationElement extends Polymer.NeonAnimationBehavior, Polymer.LegacyElementMixin, HTMLElement {
  configure(config: any): any;
}

interface PaperMenuShrinkWidthAnimationElement extends Polymer.NeonAnimationBehavior, Polymer.LegacyElementMixin, HTMLElement {
  configure(config: any): any;
}

interface PaperMenuShrinkHeightAnimationElement extends Polymer.NeonAnimationBehavior, Polymer.LegacyElementMixin, HTMLElement {
  configure(config: any): any;
}
