/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   polymer-element.js
 */

/// <reference path="lib/mixins/element-mixin.d.ts" />
/// <reference path="lib/utils/html-tag.d.ts" />

/**
 * Base class that provides the core API for Polymer's meta-programming
 * features including template stamping, data-binding, attribute deserialization,
 * and property change observation.
 */
declare class PolymerElement extends
  ElementMixin(
  HTMLElement) {
}
