/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   combo.html
 *   combo.js
 */

declare function B(): any;

declare function C(): any;

declare function A(): any;
