/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   my-element.html
 */

/**
 * I'm an HTML comment that contains JavaScript comments which must be escaped:
 *
 *   /** Danger! *\/
 *
 *   /** More danger! *\/*\/
 */
interface MyElement extends Polymer.Element {
}

interface HTMLElementTagNameMap {
  "my-element": MyElement;
}
