/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   module-a.js
 */

export {ClassA1};

declare class ClassA1 {
}

declare class ClassA2 {
}

export {ClassA2};

export {ClassB1, ClassC2Alias as ClassC2Alias2} from './module-b.js';

export * from './module-b.js';

import * as moduleC from './module-c.js';

export {moduleC as ModuleC};
