/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   module-c.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

export {ClassC1};

declare class ClassC1 {
}

export {ClassC2};

declare class ClassC2 {
}
