/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   paper-checked-element-behavior.js
 */

import {PaperRippleBehavior} from './paper-ripple-behavior.js';

export {PaperCheckedElementBehaviorImpl};

declare namespace Polymer {

  /**
   * Use `Polymer.PaperCheckedElementBehavior` to implement a custom element
   * that has a `checked` property similar to `Polymer.IronCheckedElementBehavior`
   * and is compatible with having a ripple effect.
   */
  interface PaperCheckedElementBehavior extends PaperInkyFocusBehavior, IronCheckedElementBehavior, PaperCheckedElementBehaviorImpl {

    /**
     * Synchronizes the element's checked state with its ripple effect.
     */
    _checkedChanged(): void;

    /**
     * Synchronizes the element's `active` and `checked` state.
     */
    _buttonStateChanged(): void;
  }

  const PaperCheckedElementBehavior: object;
}


/**
 * Synchronizes the element's checked state with its ripple effect.
 *    
 */
declare function _checkedChanged(): void;


/**
 * Synchronizes the element's `active` and `checked` state.
 *    
 */
declare function _buttonStateChanged(): void;
