/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   lib/utils/flush.js
 */


// tslint:disable:variable-name API description

declare module 'goog:npm.polymer.polymer.lib.utils.Flush' {

  export {enqueueDebouncer};


  /**
   * Adds a `Debouncer` to a list of globally flushable tasks.
   */
  function enqueueDebouncer(debouncer: Debouncer): void;

  export {flush};


  /**
   * Forces several classes of asynchronously queued tasks to flush:
   * - Debouncers added via `enqueueDebouncer`
   * - ShadyDOM distribution
   */
  function flush(): void;

  import {Debouncer} from 'goog:npm.polymer.polymer.lib.utils.Debounce'; // from //third_party/javascript/polymer/v2/polymer
}
