/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   lib/utils/mixin.js
 */


// tslint:disable:variable-name API description

declare module 'goog:npm.polymer.polymer.lib.utils.Mixin' {

  export {dedupingMixin};


  /**
   * Wraps an ES6 class expression mixin such that the mixin is only applied
   * if it has not already been applied its base argument. Also memoizes mixin
   * applications.
   */
  function dedupingMixin<T>(mixin: T): T;
}
