/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   lib/utils/settings.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

declare module 'goog:polymer.polymer.lib.utils.settings' {

  import {pathFromUrl} from 'goog:polymer.polymer.lib.utils.resolveUrl'; // from //third_party/javascript/polymer/v2/polymer

  export {setRootPath};


  /**
   * Sets the global rootPath property used by `ElementMixin` and
   * available via `rootPath`.
   */
  function setRootPath(path: string): void;

  export {setSanitizeDOMValue};


  /**
   * Sets the global sanitizeDOMValue available via this module's exported
   * `sanitizeDOMValue` variable.
   */
  function setSanitizeDOMValue(newSanitizeDOMValue: ((p0: any, p1: string, p2: string, p3: Node|null) => any)|undefined): void;

  export {setPassiveTouchGestures};


  /**
   * Sets `passiveTouchGestures` globally for all elements using Polymer Gestures.
   */
  function setPassiveTouchGestures(usePassive: boolean): void;

  export {setStrictTemplatePolicy};


  /**
   * Sets `strictTemplatePolicy` globally for all elements
   */
  function setStrictTemplatePolicy(useStrictPolicy: boolean): void;

  export {setAllowTemplateFromDomModule};


  /**
   * Sets `lookupTemplateFromDomModule` globally for all elements
   */
  function setAllowTemplateFromDomModule(allowDomModule: boolean): void;
}
